services:
  actual-budget:
    image: actualbudget/actual-server:25.8.0
    container_name: actual-budget
    ports:
      - 5006:5006
    environment:
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      - ACTUAL_OPENID_DISCOVERY_URL=https://auth.fwatt.dev/.well-known/openid-configuration
      - ACTUAL_OPENID_CLIENT_ID=$ACTUAL_BUDGET_CLIENT_ID
      - ACTUAL_OPENID_CLIENT_SECRET=$ACTUAL_BUDGET_CLIENT_SECRET
      - ACTUAL_OPENID_SERVER_HOSTNAME=https://actual.fwatt.dev
      - ACTUAL_OPENID_AUTH_METHOD=oauth2
      - ACTUAL_TOKEN_EXPIRATION=openid-provider
      - ACTUAL_OPENID_ENFORCE=true
      - ACTUAL_LOGIN_METHOD=openid
      - ACTUAL_ALLOWED_LOGIN_METHODS=openid
    volumes:
      - $DATA_DIR/actual-budget:/data
    healthcheck:
      test:
        - CMD-SHELL
        - node src/scripts/health-check.js
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - gw_default
networks:
  gw_default:
    external: true
